/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SetupRouteImport } from "./routes/setup"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppWalletsRouteRouteImport } from "./routes/_app/wallets/route"
import { Route as AppTasksRouteRouteImport } from "./routes/_app/tasks/route"
import { Route as AppStorageRouteRouteImport } from "./routes/_app/storage/route"
import { Route as AppSectorsRouteRouteImport } from "./routes/_app/sectors/route"
import { Route as AppProofShareRouteRouteImport } from "./routes/_app/proof-share/route"
import { Route as AppPipelineRouteRouteImport } from "./routes/_app/pipeline/route"
import { Route as AppPdpRouteRouteImport } from "./routes/_app/pdp/route"
import { Route as AppMarketRouteRouteImport } from "./routes/_app/market/route"
import { Route as AppMachinesRouteRouteImport } from "./routes/_app/machines/route"
import { Route as AppIpniRouteRouteImport } from "./routes/_app/ipni/route"
import { Route as AppWalletsIndexRouteImport } from "./routes/_app/wallets/index"
import { Route as AppTasksIndexRouteImport } from "./routes/_app/tasks/index"
import { Route as AppStorageIndexRouteImport } from "./routes/_app/storage/index"
import { Route as AppSectorsIndexRouteImport } from "./routes/_app/sectors/index"
import { Route as AppProofShareIndexRouteImport } from "./routes/_app/proof-share/index"
import { Route as AppPipelineIndexRouteImport } from "./routes/_app/pipeline/index"
import { Route as AppPdpIndexRouteImport } from "./routes/_app/pdp/index"
import { Route as AppOverviewIndexRouteImport } from "./routes/_app/overview/index"
import { Route as AppMarketIndexRouteImport } from "./routes/_app/market/index"
import { Route as AppMachinesIndexRouteImport } from "./routes/_app/machines/index"
import { Route as AppIpniIndexRouteImport } from "./routes/_app/ipni/index"
import { Route as AppConfigIndexRouteImport } from "./routes/_app/config/index"
import { Route as AppAlertsIndexRouteImport } from "./routes/_app/alerts/index"
import { Route as AppActorIndexRouteImport } from "./routes/_app/actor/index"
import { Route as AppWalletsMessagesRouteImport } from "./routes/_app/wallets/messages"
import { Route as AppWalletsListRouteImport } from "./routes/_app/wallets/list"
import { Route as AppWalletsBalanceManagerRouteImport } from "./routes/_app/wallets/balance-manager"
import { Route as AppTasksOverviewRouteImport } from "./routes/_app/tasks/overview"
import { Route as AppTasksHistoryRouteImport } from "./routes/_app/tasks/history"
import { Route as AppTasksAnalysisRouteImport } from "./routes/_app/tasks/analysis"
import { Route as AppTasksActiveRouteImport } from "./routes/_app/tasks/active"
import { Route as AppStorageUsageRouteImport } from "./routes/_app/storage/usage"
import { Route as AppStorageGcRouteImport } from "./routes/_app/storage/gc"
import { Route as AppProofShareProviderRouteImport } from "./routes/_app/proof-share/provider"
import { Route as AppProofShareClientRouteImport } from "./routes/_app/proof-share/client"
import { Route as AppPipelineStatsRouteImport } from "./routes/_app/pipeline/stats"
import { Route as AppPipelineSnapRouteImport } from "./routes/_app/pipeline/snap"
import { Route as AppPipelinePorepRouteImport } from "./routes/_app/pipeline/porep"
import { Route as AppPdpPipelinesRouteImport } from "./routes/_app/pdp/pipelines"
import { Route as AppPdpOverviewRouteImport } from "./routes/_app/pdp/overview"
import { Route as AppPdpDealsRouteImport } from "./routes/_app/pdp/deals"
import { Route as AppMarketPiecesRouteImport } from "./routes/_app/market/pieces"
import { Route as AppMarketPendingRouteImport } from "./routes/_app/market/pending"
import { Route as AppMarketBalanceRouteImport } from "./routes/_app/market/balance"
import { Route as AppMarketAsksRouteImport } from "./routes/_app/market/asks"
import { Route as AppMachinesIdRouteImport } from "./routes/_app/machines/$id"
import { Route as AppIpniSearchRouteImport } from "./routes/_app/ipni/search"
import { Route as AppIpniProvidersRouteImport } from "./routes/_app/ipni/providers"
import { Route as AppActorIdRouteImport } from "./routes/_app/actor/$id"
import { Route as AppStoragePathsRouteRouteImport } from "./routes/_app/storage/paths/route"
import { Route as AppStoragePathsIndexRouteImport } from "./routes/_app/storage/paths/index"
import { Route as AppSectorsExpirationIndexRouteImport } from "./routes/_app/sectors/expiration/index"
import { Route as AppSectorsDiagnosticsIndexRouteImport } from "./routes/_app/sectors/diagnostics/index"
import { Route as AppSectorsCcSchedulerIndexRouteImport } from "./routes/_app/sectors/cc-scheduler/index"
import { Route as AppMarketSettingsIndexRouteImport } from "./routes/_app/market/settings/index"
import { Route as AppStoragePathsStorageIdRouteImport } from "./routes/_app/storage/paths/$storageId"
import { Route as AppMarketMk20DealsRouteImport } from "./routes/_app/market/mk20/deals"
import { Route as AppMarketMk12DealsRouteImport } from "./routes/_app/market/mk12/deals"
import { Route as AppMarketMk20DealIdRouteImport } from "./routes/_app/market/mk20/deal.$id"
import { Route as AppMarketMk12DealIdRouteImport } from "./routes/_app/market/mk12/deal.$id"

const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletsRouteRoute = AppWalletsRouteRouteImport.update({
  id: "/wallets",
  path: "/wallets",
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AppRoute,
} as any)
const AppStorageRouteRoute = AppStorageRouteRouteImport.update({
  id: "/storage",
  path: "/storage",
  getParentRoute: () => AppRoute,
} as any)
const AppSectorsRouteRoute = AppSectorsRouteRouteImport.update({
  id: "/sectors",
  path: "/sectors",
  getParentRoute: () => AppRoute,
} as any)
const AppProofShareRouteRoute = AppProofShareRouteRouteImport.update({
  id: "/proof-share",
  path: "/proof-share",
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRouteRoute = AppPipelineRouteRouteImport.update({
  id: "/pipeline",
  path: "/pipeline",
  getParentRoute: () => AppRoute,
} as any)
const AppPdpRouteRoute = AppPdpRouteRouteImport.update({
  id: "/pdp",
  path: "/pdp",
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRouteRoute = AppMarketRouteRouteImport.update({
  id: "/market",
  path: "/market",
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesRouteRoute = AppMachinesRouteRouteImport.update({
  id: "/machines",
  path: "/machines",
  getParentRoute: () => AppRoute,
} as any)
const AppIpniRouteRoute = AppIpniRouteRouteImport.update({
  id: "/ipni",
  path: "/ipni",
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsIndexRoute = AppWalletsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppWalletsRouteRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppStorageIndexRoute = AppStorageIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppStorageRouteRoute,
} as any)
const AppSectorsIndexRoute = AppSectorsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppSectorsRouteRoute,
} as any)
const AppProofShareIndexRoute = AppProofShareIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppProofShareRouteRoute,
} as any)
const AppPipelineIndexRoute = AppPipelineIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppPdpIndexRoute = AppPdpIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppPdpRouteRoute,
} as any)
const AppOverviewIndexRoute = AppOverviewIndexRouteImport.update({
  id: "/overview/",
  path: "/overview/",
  getParentRoute: () => AppRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMachinesIndexRoute = AppMachinesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppMachinesRouteRoute,
} as any)
const AppIpniIndexRoute = AppIpniIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppIpniRouteRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: "/config/",
  path: "/config/",
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: "/alerts/",
  path: "/alerts/",
  getParentRoute: () => AppRoute,
} as any)
const AppActorIndexRoute = AppActorIndexRouteImport.update({
  id: "/actor/",
  path: "/actor/",
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsMessagesRoute = AppWalletsMessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => AppWalletsRouteRoute,
} as any)
const AppWalletsListRoute = AppWalletsListRouteImport.update({
  id: "/list",
  path: "/list",
  getParentRoute: () => AppWalletsRouteRoute,
} as any)
const AppWalletsBalanceManagerRoute =
  AppWalletsBalanceManagerRouteImport.update({
    id: "/balance-manager",
    path: "/balance-manager",
    getParentRoute: () => AppWalletsRouteRoute,
  } as any)
const AppTasksOverviewRoute = AppTasksOverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksHistoryRoute = AppTasksHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksAnalysisRoute = AppTasksAnalysisRouteImport.update({
  id: "/analysis",
  path: "/analysis",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksActiveRoute = AppTasksActiveRouteImport.update({
  id: "/active",
  path: "/active",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppStorageUsageRoute = AppStorageUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => AppStorageRouteRoute,
} as any)
const AppStorageGcRoute = AppStorageGcRouteImport.update({
  id: "/gc",
  path: "/gc",
  getParentRoute: () => AppStorageRouteRoute,
} as any)
const AppProofShareProviderRoute = AppProofShareProviderRouteImport.update({
  id: "/provider",
  path: "/provider",
  getParentRoute: () => AppProofShareRouteRoute,
} as any)
const AppProofShareClientRoute = AppProofShareClientRouteImport.update({
  id: "/client",
  path: "/client",
  getParentRoute: () => AppProofShareRouteRoute,
} as any)
const AppPipelineStatsRoute = AppPipelineStatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppPipelineSnapRoute = AppPipelineSnapRouteImport.update({
  id: "/snap",
  path: "/snap",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppPipelinePorepRoute = AppPipelinePorepRouteImport.update({
  id: "/porep",
  path: "/porep",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppPdpPipelinesRoute = AppPdpPipelinesRouteImport.update({
  id: "/pipelines",
  path: "/pipelines",
  getParentRoute: () => AppPdpRouteRoute,
} as any)
const AppPdpOverviewRoute = AppPdpOverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => AppPdpRouteRoute,
} as any)
const AppPdpDealsRoute = AppPdpDealsRouteImport.update({
  id: "/deals",
  path: "/deals",
  getParentRoute: () => AppPdpRouteRoute,
} as any)
const AppMarketPiecesRoute = AppMarketPiecesRouteImport.update({
  id: "/pieces",
  path: "/pieces",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketPendingRoute = AppMarketPendingRouteImport.update({
  id: "/pending",
  path: "/pending",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketBalanceRoute = AppMarketBalanceRouteImport.update({
  id: "/balance",
  path: "/balance",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketAsksRoute = AppMarketAsksRouteImport.update({
  id: "/asks",
  path: "/asks",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMachinesIdRoute = AppMachinesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => AppMachinesRouteRoute,
} as any)
const AppIpniSearchRoute = AppIpniSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => AppIpniRouteRoute,
} as any)
const AppIpniProvidersRoute = AppIpniProvidersRouteImport.update({
  id: "/providers",
  path: "/providers",
  getParentRoute: () => AppIpniRouteRoute,
} as any)
const AppActorIdRoute = AppActorIdRouteImport.update({
  id: "/actor/$id",
  path: "/actor/$id",
  getParentRoute: () => AppRoute,
} as any)
const AppStoragePathsRouteRoute = AppStoragePathsRouteRouteImport.update({
  id: "/paths",
  path: "/paths",
  getParentRoute: () => AppStorageRouteRoute,
} as any)
const AppStoragePathsIndexRoute = AppStoragePathsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppStoragePathsRouteRoute,
} as any)
const AppSectorsExpirationIndexRoute =
  AppSectorsExpirationIndexRouteImport.update({
    id: "/expiration/",
    path: "/expiration/",
    getParentRoute: () => AppSectorsRouteRoute,
  } as any)
const AppSectorsDiagnosticsIndexRoute =
  AppSectorsDiagnosticsIndexRouteImport.update({
    id: "/diagnostics/",
    path: "/diagnostics/",
    getParentRoute: () => AppSectorsRouteRoute,
  } as any)
const AppSectorsCcSchedulerIndexRoute =
  AppSectorsCcSchedulerIndexRouteImport.update({
    id: "/cc-scheduler/",
    path: "/cc-scheduler/",
    getParentRoute: () => AppSectorsRouteRoute,
  } as any)
const AppMarketSettingsIndexRoute = AppMarketSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppStoragePathsStorageIdRoute =
  AppStoragePathsStorageIdRouteImport.update({
    id: "/$storageId",
    path: "/$storageId",
    getParentRoute: () => AppStoragePathsRouteRoute,
  } as any)
const AppMarketMk20DealsRoute = AppMarketMk20DealsRouteImport.update({
  id: "/mk20/deals",
  path: "/mk20/deals",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketMk12DealsRoute = AppMarketMk12DealsRouteImport.update({
  id: "/mk12/deals",
  path: "/mk12/deals",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketMk20DealIdRoute = AppMarketMk20DealIdRouteImport.update({
  id: "/mk20/deal/$id",
  path: "/mk20/deal/$id",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketMk12DealIdRoute = AppMarketMk12DealIdRouteImport.update({
  id: "/mk12/deal/$id",
  path: "/mk12/deal/$id",
  getParentRoute: () => AppMarketRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/setup": typeof SetupRoute
  "/ipni": typeof AppIpniRouteRouteWithChildren
  "/machines": typeof AppMachinesRouteRouteWithChildren
  "/market": typeof AppMarketRouteRouteWithChildren
  "/pdp": typeof AppPdpRouteRouteWithChildren
  "/pipeline": typeof AppPipelineRouteRouteWithChildren
  "/proof-share": typeof AppProofShareRouteRouteWithChildren
  "/sectors": typeof AppSectorsRouteRouteWithChildren
  "/storage": typeof AppStorageRouteRouteWithChildren
  "/tasks": typeof AppTasksRouteRouteWithChildren
  "/wallets": typeof AppWalletsRouteRouteWithChildren
  "/storage/paths": typeof AppStoragePathsRouteRouteWithChildren
  "/actor/$id": typeof AppActorIdRoute
  "/ipni/providers": typeof AppIpniProvidersRoute
  "/ipni/search": typeof AppIpniSearchRoute
  "/machines/$id": typeof AppMachinesIdRoute
  "/market/asks": typeof AppMarketAsksRoute
  "/market/balance": typeof AppMarketBalanceRoute
  "/market/pending": typeof AppMarketPendingRoute
  "/market/pieces": typeof AppMarketPiecesRoute
  "/pdp/deals": typeof AppPdpDealsRoute
  "/pdp/overview": typeof AppPdpOverviewRoute
  "/pdp/pipelines": typeof AppPdpPipelinesRoute
  "/pipeline/porep": typeof AppPipelinePorepRoute
  "/pipeline/snap": typeof AppPipelineSnapRoute
  "/pipeline/stats": typeof AppPipelineStatsRoute
  "/proof-share/client": typeof AppProofShareClientRoute
  "/proof-share/provider": typeof AppProofShareProviderRoute
  "/storage/gc": typeof AppStorageGcRoute
  "/storage/usage": typeof AppStorageUsageRoute
  "/tasks/active": typeof AppTasksActiveRoute
  "/tasks/analysis": typeof AppTasksAnalysisRoute
  "/tasks/history": typeof AppTasksHistoryRoute
  "/tasks/overview": typeof AppTasksOverviewRoute
  "/wallets/balance-manager": typeof AppWalletsBalanceManagerRoute
  "/wallets/list": typeof AppWalletsListRoute
  "/wallets/messages": typeof AppWalletsMessagesRoute
  "/actor/": typeof AppActorIndexRoute
  "/alerts/": typeof AppAlertsIndexRoute
  "/config/": typeof AppConfigIndexRoute
  "/ipni/": typeof AppIpniIndexRoute
  "/machines/": typeof AppMachinesIndexRoute
  "/market/": typeof AppMarketIndexRoute
  "/overview/": typeof AppOverviewIndexRoute
  "/pdp/": typeof AppPdpIndexRoute
  "/pipeline/": typeof AppPipelineIndexRoute
  "/proof-share/": typeof AppProofShareIndexRoute
  "/sectors/": typeof AppSectorsIndexRoute
  "/storage/": typeof AppStorageIndexRoute
  "/tasks/": typeof AppTasksIndexRoute
  "/wallets/": typeof AppWalletsIndexRoute
  "/market/mk12/deals": typeof AppMarketMk12DealsRoute
  "/market/mk20/deals": typeof AppMarketMk20DealsRoute
  "/storage/paths/$storageId": typeof AppStoragePathsStorageIdRoute
  "/market/settings/": typeof AppMarketSettingsIndexRoute
  "/sectors/cc-scheduler/": typeof AppSectorsCcSchedulerIndexRoute
  "/sectors/diagnostics/": typeof AppSectorsDiagnosticsIndexRoute
  "/sectors/expiration/": typeof AppSectorsExpirationIndexRoute
  "/storage/paths/": typeof AppStoragePathsIndexRoute
  "/market/mk12/deal/$id": typeof AppMarketMk12DealIdRoute
  "/market/mk20/deal/$id": typeof AppMarketMk20DealIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/setup": typeof SetupRoute
  "/actor/$id": typeof AppActorIdRoute
  "/ipni/providers": typeof AppIpniProvidersRoute
  "/ipni/search": typeof AppIpniSearchRoute
  "/machines/$id": typeof AppMachinesIdRoute
  "/market/asks": typeof AppMarketAsksRoute
  "/market/balance": typeof AppMarketBalanceRoute
  "/market/pending": typeof AppMarketPendingRoute
  "/market/pieces": typeof AppMarketPiecesRoute
  "/pdp/deals": typeof AppPdpDealsRoute
  "/pdp/overview": typeof AppPdpOverviewRoute
  "/pdp/pipelines": typeof AppPdpPipelinesRoute
  "/pipeline/porep": typeof AppPipelinePorepRoute
  "/pipeline/snap": typeof AppPipelineSnapRoute
  "/pipeline/stats": typeof AppPipelineStatsRoute
  "/proof-share/client": typeof AppProofShareClientRoute
  "/proof-share/provider": typeof AppProofShareProviderRoute
  "/storage/gc": typeof AppStorageGcRoute
  "/storage/usage": typeof AppStorageUsageRoute
  "/tasks/active": typeof AppTasksActiveRoute
  "/tasks/analysis": typeof AppTasksAnalysisRoute
  "/tasks/history": typeof AppTasksHistoryRoute
  "/tasks/overview": typeof AppTasksOverviewRoute
  "/wallets/balance-manager": typeof AppWalletsBalanceManagerRoute
  "/wallets/list": typeof AppWalletsListRoute
  "/wallets/messages": typeof AppWalletsMessagesRoute
  "/actor": typeof AppActorIndexRoute
  "/alerts": typeof AppAlertsIndexRoute
  "/config": typeof AppConfigIndexRoute
  "/ipni": typeof AppIpniIndexRoute
  "/machines": typeof AppMachinesIndexRoute
  "/market": typeof AppMarketIndexRoute
  "/overview": typeof AppOverviewIndexRoute
  "/pdp": typeof AppPdpIndexRoute
  "/pipeline": typeof AppPipelineIndexRoute
  "/proof-share": typeof AppProofShareIndexRoute
  "/sectors": typeof AppSectorsIndexRoute
  "/storage": typeof AppStorageIndexRoute
  "/tasks": typeof AppTasksIndexRoute
  "/wallets": typeof AppWalletsIndexRoute
  "/market/mk12/deals": typeof AppMarketMk12DealsRoute
  "/market/mk20/deals": typeof AppMarketMk20DealsRoute
  "/storage/paths/$storageId": typeof AppStoragePathsStorageIdRoute
  "/market/settings": typeof AppMarketSettingsIndexRoute
  "/sectors/cc-scheduler": typeof AppSectorsCcSchedulerIndexRoute
  "/sectors/diagnostics": typeof AppSectorsDiagnosticsIndexRoute
  "/sectors/expiration": typeof AppSectorsExpirationIndexRoute
  "/storage/paths": typeof AppStoragePathsIndexRoute
  "/market/mk12/deal/$id": typeof AppMarketMk12DealIdRoute
  "/market/mk20/deal/$id": typeof AppMarketMk20DealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/setup": typeof SetupRoute
  "/_app/ipni": typeof AppIpniRouteRouteWithChildren
  "/_app/machines": typeof AppMachinesRouteRouteWithChildren
  "/_app/market": typeof AppMarketRouteRouteWithChildren
  "/_app/pdp": typeof AppPdpRouteRouteWithChildren
  "/_app/pipeline": typeof AppPipelineRouteRouteWithChildren
  "/_app/proof-share": typeof AppProofShareRouteRouteWithChildren
  "/_app/sectors": typeof AppSectorsRouteRouteWithChildren
  "/_app/storage": typeof AppStorageRouteRouteWithChildren
  "/_app/tasks": typeof AppTasksRouteRouteWithChildren
  "/_app/wallets": typeof AppWalletsRouteRouteWithChildren
  "/_app/storage/paths": typeof AppStoragePathsRouteRouteWithChildren
  "/_app/actor/$id": typeof AppActorIdRoute
  "/_app/ipni/providers": typeof AppIpniProvidersRoute
  "/_app/ipni/search": typeof AppIpniSearchRoute
  "/_app/machines/$id": typeof AppMachinesIdRoute
  "/_app/market/asks": typeof AppMarketAsksRoute
  "/_app/market/balance": typeof AppMarketBalanceRoute
  "/_app/market/pending": typeof AppMarketPendingRoute
  "/_app/market/pieces": typeof AppMarketPiecesRoute
  "/_app/pdp/deals": typeof AppPdpDealsRoute
  "/_app/pdp/overview": typeof AppPdpOverviewRoute
  "/_app/pdp/pipelines": typeof AppPdpPipelinesRoute
  "/_app/pipeline/porep": typeof AppPipelinePorepRoute
  "/_app/pipeline/snap": typeof AppPipelineSnapRoute
  "/_app/pipeline/stats": typeof AppPipelineStatsRoute
  "/_app/proof-share/client": typeof AppProofShareClientRoute
  "/_app/proof-share/provider": typeof AppProofShareProviderRoute
  "/_app/storage/gc": typeof AppStorageGcRoute
  "/_app/storage/usage": typeof AppStorageUsageRoute
  "/_app/tasks/active": typeof AppTasksActiveRoute
  "/_app/tasks/analysis": typeof AppTasksAnalysisRoute
  "/_app/tasks/history": typeof AppTasksHistoryRoute
  "/_app/tasks/overview": typeof AppTasksOverviewRoute
  "/_app/wallets/balance-manager": typeof AppWalletsBalanceManagerRoute
  "/_app/wallets/list": typeof AppWalletsListRoute
  "/_app/wallets/messages": typeof AppWalletsMessagesRoute
  "/_app/actor/": typeof AppActorIndexRoute
  "/_app/alerts/": typeof AppAlertsIndexRoute
  "/_app/config/": typeof AppConfigIndexRoute
  "/_app/ipni/": typeof AppIpniIndexRoute
  "/_app/machines/": typeof AppMachinesIndexRoute
  "/_app/market/": typeof AppMarketIndexRoute
  "/_app/overview/": typeof AppOverviewIndexRoute
  "/_app/pdp/": typeof AppPdpIndexRoute
  "/_app/pipeline/": typeof AppPipelineIndexRoute
  "/_app/proof-share/": typeof AppProofShareIndexRoute
  "/_app/sectors/": typeof AppSectorsIndexRoute
  "/_app/storage/": typeof AppStorageIndexRoute
  "/_app/tasks/": typeof AppTasksIndexRoute
  "/_app/wallets/": typeof AppWalletsIndexRoute
  "/_app/market/mk12/deals": typeof AppMarketMk12DealsRoute
  "/_app/market/mk20/deals": typeof AppMarketMk20DealsRoute
  "/_app/storage/paths/$storageId": typeof AppStoragePathsStorageIdRoute
  "/_app/market/settings/": typeof AppMarketSettingsIndexRoute
  "/_app/sectors/cc-scheduler/": typeof AppSectorsCcSchedulerIndexRoute
  "/_app/sectors/diagnostics/": typeof AppSectorsDiagnosticsIndexRoute
  "/_app/sectors/expiration/": typeof AppSectorsExpirationIndexRoute
  "/_app/storage/paths/": typeof AppStoragePathsIndexRoute
  "/_app/market/mk12/deal/$id": typeof AppMarketMk12DealIdRoute
  "/_app/market/mk20/deal/$id": typeof AppMarketMk20DealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/setup"
    | "/ipni"
    | "/machines"
    | "/market"
    | "/pdp"
    | "/pipeline"
    | "/proof-share"
    | "/sectors"
    | "/storage"
    | "/tasks"
    | "/wallets"
    | "/storage/paths"
    | "/actor/$id"
    | "/ipni/providers"
    | "/ipni/search"
    | "/machines/$id"
    | "/market/asks"
    | "/market/balance"
    | "/market/pending"
    | "/market/pieces"
    | "/pdp/deals"
    | "/pdp/overview"
    | "/pdp/pipelines"
    | "/pipeline/porep"
    | "/pipeline/snap"
    | "/pipeline/stats"
    | "/proof-share/client"
    | "/proof-share/provider"
    | "/storage/gc"
    | "/storage/usage"
    | "/tasks/active"
    | "/tasks/analysis"
    | "/tasks/history"
    | "/tasks/overview"
    | "/wallets/balance-manager"
    | "/wallets/list"
    | "/wallets/messages"
    | "/actor/"
    | "/alerts/"
    | "/config/"
    | "/ipni/"
    | "/machines/"
    | "/market/"
    | "/overview/"
    | "/pdp/"
    | "/pipeline/"
    | "/proof-share/"
    | "/sectors/"
    | "/storage/"
    | "/tasks/"
    | "/wallets/"
    | "/market/mk12/deals"
    | "/market/mk20/deals"
    | "/storage/paths/$storageId"
    | "/market/settings/"
    | "/sectors/cc-scheduler/"
    | "/sectors/diagnostics/"
    | "/sectors/expiration/"
    | "/storage/paths/"
    | "/market/mk12/deal/$id"
    | "/market/mk20/deal/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/setup"
    | "/actor/$id"
    | "/ipni/providers"
    | "/ipni/search"
    | "/machines/$id"
    | "/market/asks"
    | "/market/balance"
    | "/market/pending"
    | "/market/pieces"
    | "/pdp/deals"
    | "/pdp/overview"
    | "/pdp/pipelines"
    | "/pipeline/porep"
    | "/pipeline/snap"
    | "/pipeline/stats"
    | "/proof-share/client"
    | "/proof-share/provider"
    | "/storage/gc"
    | "/storage/usage"
    | "/tasks/active"
    | "/tasks/analysis"
    | "/tasks/history"
    | "/tasks/overview"
    | "/wallets/balance-manager"
    | "/wallets/list"
    | "/wallets/messages"
    | "/actor"
    | "/alerts"
    | "/config"
    | "/ipni"
    | "/machines"
    | "/market"
    | "/overview"
    | "/pdp"
    | "/pipeline"
    | "/proof-share"
    | "/sectors"
    | "/storage"
    | "/tasks"
    | "/wallets"
    | "/market/mk12/deals"
    | "/market/mk20/deals"
    | "/storage/paths/$storageId"
    | "/market/settings"
    | "/sectors/cc-scheduler"
    | "/sectors/diagnostics"
    | "/sectors/expiration"
    | "/storage/paths"
    | "/market/mk12/deal/$id"
    | "/market/mk20/deal/$id"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/setup"
    | "/_app/ipni"
    | "/_app/machines"
    | "/_app/market"
    | "/_app/pdp"
    | "/_app/pipeline"
    | "/_app/proof-share"
    | "/_app/sectors"
    | "/_app/storage"
    | "/_app/tasks"
    | "/_app/wallets"
    | "/_app/storage/paths"
    | "/_app/actor/$id"
    | "/_app/ipni/providers"
    | "/_app/ipni/search"
    | "/_app/machines/$id"
    | "/_app/market/asks"
    | "/_app/market/balance"
    | "/_app/market/pending"
    | "/_app/market/pieces"
    | "/_app/pdp/deals"
    | "/_app/pdp/overview"
    | "/_app/pdp/pipelines"
    | "/_app/pipeline/porep"
    | "/_app/pipeline/snap"
    | "/_app/pipeline/stats"
    | "/_app/proof-share/client"
    | "/_app/proof-share/provider"
    | "/_app/storage/gc"
    | "/_app/storage/usage"
    | "/_app/tasks/active"
    | "/_app/tasks/analysis"
    | "/_app/tasks/history"
    | "/_app/tasks/overview"
    | "/_app/wallets/balance-manager"
    | "/_app/wallets/list"
    | "/_app/wallets/messages"
    | "/_app/actor/"
    | "/_app/alerts/"
    | "/_app/config/"
    | "/_app/ipni/"
    | "/_app/machines/"
    | "/_app/market/"
    | "/_app/overview/"
    | "/_app/pdp/"
    | "/_app/pipeline/"
    | "/_app/proof-share/"
    | "/_app/sectors/"
    | "/_app/storage/"
    | "/_app/tasks/"
    | "/_app/wallets/"
    | "/_app/market/mk12/deals"
    | "/_app/market/mk20/deals"
    | "/_app/storage/paths/$storageId"
    | "/_app/market/settings/"
    | "/_app/sectors/cc-scheduler/"
    | "/_app/sectors/diagnostics/"
    | "/_app/sectors/expiration/"
    | "/_app/storage/paths/"
    | "/_app/market/mk12/deal/$id"
    | "/_app/market/mk20/deal/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/setup": {
      id: "/setup"
      path: "/setup"
      fullPath: "/setup"
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/wallets": {
      id: "/_app/wallets"
      path: "/wallets"
      fullPath: "/wallets"
      preLoaderRoute: typeof AppWalletsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tasks": {
      id: "/_app/tasks"
      path: "/tasks"
      fullPath: "/tasks"
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/storage": {
      id: "/_app/storage"
      path: "/storage"
      fullPath: "/storage"
      preLoaderRoute: typeof AppStorageRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/sectors": {
      id: "/_app/sectors"
      path: "/sectors"
      fullPath: "/sectors"
      preLoaderRoute: typeof AppSectorsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/proof-share": {
      id: "/_app/proof-share"
      path: "/proof-share"
      fullPath: "/proof-share"
      preLoaderRoute: typeof AppProofShareRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/pipeline": {
      id: "/_app/pipeline"
      path: "/pipeline"
      fullPath: "/pipeline"
      preLoaderRoute: typeof AppPipelineRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/pdp": {
      id: "/_app/pdp"
      path: "/pdp"
      fullPath: "/pdp"
      preLoaderRoute: typeof AppPdpRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/market": {
      id: "/_app/market"
      path: "/market"
      fullPath: "/market"
      preLoaderRoute: typeof AppMarketRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/machines": {
      id: "/_app/machines"
      path: "/machines"
      fullPath: "/machines"
      preLoaderRoute: typeof AppMachinesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/ipni": {
      id: "/_app/ipni"
      path: "/ipni"
      fullPath: "/ipni"
      preLoaderRoute: typeof AppIpniRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/wallets/": {
      id: "/_app/wallets/"
      path: "/"
      fullPath: "/wallets/"
      preLoaderRoute: typeof AppWalletsIndexRouteImport
      parentRoute: typeof AppWalletsRouteRoute
    }
    "/_app/tasks/": {
      id: "/_app/tasks/"
      path: "/"
      fullPath: "/tasks/"
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/storage/": {
      id: "/_app/storage/"
      path: "/"
      fullPath: "/storage/"
      preLoaderRoute: typeof AppStorageIndexRouteImport
      parentRoute: typeof AppStorageRouteRoute
    }
    "/_app/sectors/": {
      id: "/_app/sectors/"
      path: "/"
      fullPath: "/sectors/"
      preLoaderRoute: typeof AppSectorsIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/proof-share/": {
      id: "/_app/proof-share/"
      path: "/"
      fullPath: "/proof-share/"
      preLoaderRoute: typeof AppProofShareIndexRouteImport
      parentRoute: typeof AppProofShareRouteRoute
    }
    "/_app/pipeline/": {
      id: "/_app/pipeline/"
      path: "/"
      fullPath: "/pipeline/"
      preLoaderRoute: typeof AppPipelineIndexRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/pdp/": {
      id: "/_app/pdp/"
      path: "/"
      fullPath: "/pdp/"
      preLoaderRoute: typeof AppPdpIndexRouteImport
      parentRoute: typeof AppPdpRouteRoute
    }
    "/_app/overview/": {
      id: "/_app/overview/"
      path: "/overview"
      fullPath: "/overview/"
      preLoaderRoute: typeof AppOverviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/market/": {
      id: "/_app/market/"
      path: "/"
      fullPath: "/market/"
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/machines/": {
      id: "/_app/machines/"
      path: "/"
      fullPath: "/machines/"
      preLoaderRoute: typeof AppMachinesIndexRouteImport
      parentRoute: typeof AppMachinesRouteRoute
    }
    "/_app/ipni/": {
      id: "/_app/ipni/"
      path: "/"
      fullPath: "/ipni/"
      preLoaderRoute: typeof AppIpniIndexRouteImport
      parentRoute: typeof AppIpniRouteRoute
    }
    "/_app/config/": {
      id: "/_app/config/"
      path: "/config"
      fullPath: "/config/"
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/alerts/": {
      id: "/_app/alerts/"
      path: "/alerts"
      fullPath: "/alerts/"
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/actor/": {
      id: "/_app/actor/"
      path: "/actor"
      fullPath: "/actor/"
      preLoaderRoute: typeof AppActorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/wallets/messages": {
      id: "/_app/wallets/messages"
      path: "/messages"
      fullPath: "/wallets/messages"
      preLoaderRoute: typeof AppWalletsMessagesRouteImport
      parentRoute: typeof AppWalletsRouteRoute
    }
    "/_app/wallets/list": {
      id: "/_app/wallets/list"
      path: "/list"
      fullPath: "/wallets/list"
      preLoaderRoute: typeof AppWalletsListRouteImport
      parentRoute: typeof AppWalletsRouteRoute
    }
    "/_app/wallets/balance-manager": {
      id: "/_app/wallets/balance-manager"
      path: "/balance-manager"
      fullPath: "/wallets/balance-manager"
      preLoaderRoute: typeof AppWalletsBalanceManagerRouteImport
      parentRoute: typeof AppWalletsRouteRoute
    }
    "/_app/tasks/overview": {
      id: "/_app/tasks/overview"
      path: "/overview"
      fullPath: "/tasks/overview"
      preLoaderRoute: typeof AppTasksOverviewRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/tasks/history": {
      id: "/_app/tasks/history"
      path: "/history"
      fullPath: "/tasks/history"
      preLoaderRoute: typeof AppTasksHistoryRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/tasks/analysis": {
      id: "/_app/tasks/analysis"
      path: "/analysis"
      fullPath: "/tasks/analysis"
      preLoaderRoute: typeof AppTasksAnalysisRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/tasks/active": {
      id: "/_app/tasks/active"
      path: "/active"
      fullPath: "/tasks/active"
      preLoaderRoute: typeof AppTasksActiveRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/storage/usage": {
      id: "/_app/storage/usage"
      path: "/usage"
      fullPath: "/storage/usage"
      preLoaderRoute: typeof AppStorageUsageRouteImport
      parentRoute: typeof AppStorageRouteRoute
    }
    "/_app/storage/gc": {
      id: "/_app/storage/gc"
      path: "/gc"
      fullPath: "/storage/gc"
      preLoaderRoute: typeof AppStorageGcRouteImport
      parentRoute: typeof AppStorageRouteRoute
    }
    "/_app/proof-share/provider": {
      id: "/_app/proof-share/provider"
      path: "/provider"
      fullPath: "/proof-share/provider"
      preLoaderRoute: typeof AppProofShareProviderRouteImport
      parentRoute: typeof AppProofShareRouteRoute
    }
    "/_app/proof-share/client": {
      id: "/_app/proof-share/client"
      path: "/client"
      fullPath: "/proof-share/client"
      preLoaderRoute: typeof AppProofShareClientRouteImport
      parentRoute: typeof AppProofShareRouteRoute
    }
    "/_app/pipeline/stats": {
      id: "/_app/pipeline/stats"
      path: "/stats"
      fullPath: "/pipeline/stats"
      preLoaderRoute: typeof AppPipelineStatsRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/pipeline/snap": {
      id: "/_app/pipeline/snap"
      path: "/snap"
      fullPath: "/pipeline/snap"
      preLoaderRoute: typeof AppPipelineSnapRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/pipeline/porep": {
      id: "/_app/pipeline/porep"
      path: "/porep"
      fullPath: "/pipeline/porep"
      preLoaderRoute: typeof AppPipelinePorepRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/pdp/pipelines": {
      id: "/_app/pdp/pipelines"
      path: "/pipelines"
      fullPath: "/pdp/pipelines"
      preLoaderRoute: typeof AppPdpPipelinesRouteImport
      parentRoute: typeof AppPdpRouteRoute
    }
    "/_app/pdp/overview": {
      id: "/_app/pdp/overview"
      path: "/overview"
      fullPath: "/pdp/overview"
      preLoaderRoute: typeof AppPdpOverviewRouteImport
      parentRoute: typeof AppPdpRouteRoute
    }
    "/_app/pdp/deals": {
      id: "/_app/pdp/deals"
      path: "/deals"
      fullPath: "/pdp/deals"
      preLoaderRoute: typeof AppPdpDealsRouteImport
      parentRoute: typeof AppPdpRouteRoute
    }
    "/_app/market/pieces": {
      id: "/_app/market/pieces"
      path: "/pieces"
      fullPath: "/market/pieces"
      preLoaderRoute: typeof AppMarketPiecesRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/pending": {
      id: "/_app/market/pending"
      path: "/pending"
      fullPath: "/market/pending"
      preLoaderRoute: typeof AppMarketPendingRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/balance": {
      id: "/_app/market/balance"
      path: "/balance"
      fullPath: "/market/balance"
      preLoaderRoute: typeof AppMarketBalanceRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/asks": {
      id: "/_app/market/asks"
      path: "/asks"
      fullPath: "/market/asks"
      preLoaderRoute: typeof AppMarketAsksRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/machines/$id": {
      id: "/_app/machines/$id"
      path: "/$id"
      fullPath: "/machines/$id"
      preLoaderRoute: typeof AppMachinesIdRouteImport
      parentRoute: typeof AppMachinesRouteRoute
    }
    "/_app/ipni/search": {
      id: "/_app/ipni/search"
      path: "/search"
      fullPath: "/ipni/search"
      preLoaderRoute: typeof AppIpniSearchRouteImport
      parentRoute: typeof AppIpniRouteRoute
    }
    "/_app/ipni/providers": {
      id: "/_app/ipni/providers"
      path: "/providers"
      fullPath: "/ipni/providers"
      preLoaderRoute: typeof AppIpniProvidersRouteImport
      parentRoute: typeof AppIpniRouteRoute
    }
    "/_app/actor/$id": {
      id: "/_app/actor/$id"
      path: "/actor/$id"
      fullPath: "/actor/$id"
      preLoaderRoute: typeof AppActorIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/storage/paths": {
      id: "/_app/storage/paths"
      path: "/paths"
      fullPath: "/storage/paths"
      preLoaderRoute: typeof AppStoragePathsRouteRouteImport
      parentRoute: typeof AppStorageRouteRoute
    }
    "/_app/storage/paths/": {
      id: "/_app/storage/paths/"
      path: "/"
      fullPath: "/storage/paths/"
      preLoaderRoute: typeof AppStoragePathsIndexRouteImport
      parentRoute: typeof AppStoragePathsRouteRoute
    }
    "/_app/sectors/expiration/": {
      id: "/_app/sectors/expiration/"
      path: "/expiration"
      fullPath: "/sectors/expiration/"
      preLoaderRoute: typeof AppSectorsExpirationIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/sectors/diagnostics/": {
      id: "/_app/sectors/diagnostics/"
      path: "/diagnostics"
      fullPath: "/sectors/diagnostics/"
      preLoaderRoute: typeof AppSectorsDiagnosticsIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/sectors/cc-scheduler/": {
      id: "/_app/sectors/cc-scheduler/"
      path: "/cc-scheduler"
      fullPath: "/sectors/cc-scheduler/"
      preLoaderRoute: typeof AppSectorsCcSchedulerIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/market/settings/": {
      id: "/_app/market/settings/"
      path: "/settings"
      fullPath: "/market/settings/"
      preLoaderRoute: typeof AppMarketSettingsIndexRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/storage/paths/$storageId": {
      id: "/_app/storage/paths/$storageId"
      path: "/$storageId"
      fullPath: "/storage/paths/$storageId"
      preLoaderRoute: typeof AppStoragePathsStorageIdRouteImport
      parentRoute: typeof AppStoragePathsRouteRoute
    }
    "/_app/market/mk20/deals": {
      id: "/_app/market/mk20/deals"
      path: "/mk20/deals"
      fullPath: "/market/mk20/deals"
      preLoaderRoute: typeof AppMarketMk20DealsRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/mk12/deals": {
      id: "/_app/market/mk12/deals"
      path: "/mk12/deals"
      fullPath: "/market/mk12/deals"
      preLoaderRoute: typeof AppMarketMk12DealsRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/mk20/deal/$id": {
      id: "/_app/market/mk20/deal/$id"
      path: "/mk20/deal/$id"
      fullPath: "/market/mk20/deal/$id"
      preLoaderRoute: typeof AppMarketMk20DealIdRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/mk12/deal/$id": {
      id: "/_app/market/mk12/deal/$id"
      path: "/mk12/deal/$id"
      fullPath: "/market/mk12/deal/$id"
      preLoaderRoute: typeof AppMarketMk12DealIdRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
  }
}

interface AppIpniRouteRouteChildren {
  AppIpniProvidersRoute: typeof AppIpniProvidersRoute
  AppIpniSearchRoute: typeof AppIpniSearchRoute
  AppIpniIndexRoute: typeof AppIpniIndexRoute
}

const AppIpniRouteRouteChildren: AppIpniRouteRouteChildren = {
  AppIpniProvidersRoute: AppIpniProvidersRoute,
  AppIpniSearchRoute: AppIpniSearchRoute,
  AppIpniIndexRoute: AppIpniIndexRoute,
}

const AppIpniRouteRouteWithChildren = AppIpniRouteRoute._addFileChildren(
  AppIpniRouteRouteChildren,
)

interface AppMachinesRouteRouteChildren {
  AppMachinesIdRoute: typeof AppMachinesIdRoute
  AppMachinesIndexRoute: typeof AppMachinesIndexRoute
}

const AppMachinesRouteRouteChildren: AppMachinesRouteRouteChildren = {
  AppMachinesIdRoute: AppMachinesIdRoute,
  AppMachinesIndexRoute: AppMachinesIndexRoute,
}

const AppMachinesRouteRouteWithChildren =
  AppMachinesRouteRoute._addFileChildren(AppMachinesRouteRouteChildren)

interface AppMarketRouteRouteChildren {
  AppMarketAsksRoute: typeof AppMarketAsksRoute
  AppMarketBalanceRoute: typeof AppMarketBalanceRoute
  AppMarketPendingRoute: typeof AppMarketPendingRoute
  AppMarketPiecesRoute: typeof AppMarketPiecesRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppMarketMk12DealsRoute: typeof AppMarketMk12DealsRoute
  AppMarketMk20DealsRoute: typeof AppMarketMk20DealsRoute
  AppMarketSettingsIndexRoute: typeof AppMarketSettingsIndexRoute
  AppMarketMk12DealIdRoute: typeof AppMarketMk12DealIdRoute
  AppMarketMk20DealIdRoute: typeof AppMarketMk20DealIdRoute
}

const AppMarketRouteRouteChildren: AppMarketRouteRouteChildren = {
  AppMarketAsksRoute: AppMarketAsksRoute,
  AppMarketBalanceRoute: AppMarketBalanceRoute,
  AppMarketPendingRoute: AppMarketPendingRoute,
  AppMarketPiecesRoute: AppMarketPiecesRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppMarketMk12DealsRoute: AppMarketMk12DealsRoute,
  AppMarketMk20DealsRoute: AppMarketMk20DealsRoute,
  AppMarketSettingsIndexRoute: AppMarketSettingsIndexRoute,
  AppMarketMk12DealIdRoute: AppMarketMk12DealIdRoute,
  AppMarketMk20DealIdRoute: AppMarketMk20DealIdRoute,
}

const AppMarketRouteRouteWithChildren = AppMarketRouteRoute._addFileChildren(
  AppMarketRouteRouteChildren,
)

interface AppPdpRouteRouteChildren {
  AppPdpDealsRoute: typeof AppPdpDealsRoute
  AppPdpOverviewRoute: typeof AppPdpOverviewRoute
  AppPdpPipelinesRoute: typeof AppPdpPipelinesRoute
  AppPdpIndexRoute: typeof AppPdpIndexRoute
}

const AppPdpRouteRouteChildren: AppPdpRouteRouteChildren = {
  AppPdpDealsRoute: AppPdpDealsRoute,
  AppPdpOverviewRoute: AppPdpOverviewRoute,
  AppPdpPipelinesRoute: AppPdpPipelinesRoute,
  AppPdpIndexRoute: AppPdpIndexRoute,
}

const AppPdpRouteRouteWithChildren = AppPdpRouteRoute._addFileChildren(
  AppPdpRouteRouteChildren,
)

interface AppPipelineRouteRouteChildren {
  AppPipelinePorepRoute: typeof AppPipelinePorepRoute
  AppPipelineSnapRoute: typeof AppPipelineSnapRoute
  AppPipelineStatsRoute: typeof AppPipelineStatsRoute
  AppPipelineIndexRoute: typeof AppPipelineIndexRoute
}

const AppPipelineRouteRouteChildren: AppPipelineRouteRouteChildren = {
  AppPipelinePorepRoute: AppPipelinePorepRoute,
  AppPipelineSnapRoute: AppPipelineSnapRoute,
  AppPipelineStatsRoute: AppPipelineStatsRoute,
  AppPipelineIndexRoute: AppPipelineIndexRoute,
}

const AppPipelineRouteRouteWithChildren =
  AppPipelineRouteRoute._addFileChildren(AppPipelineRouteRouteChildren)

interface AppProofShareRouteRouteChildren {
  AppProofShareClientRoute: typeof AppProofShareClientRoute
  AppProofShareProviderRoute: typeof AppProofShareProviderRoute
  AppProofShareIndexRoute: typeof AppProofShareIndexRoute
}

const AppProofShareRouteRouteChildren: AppProofShareRouteRouteChildren = {
  AppProofShareClientRoute: AppProofShareClientRoute,
  AppProofShareProviderRoute: AppProofShareProviderRoute,
  AppProofShareIndexRoute: AppProofShareIndexRoute,
}

const AppProofShareRouteRouteWithChildren =
  AppProofShareRouteRoute._addFileChildren(AppProofShareRouteRouteChildren)

interface AppSectorsRouteRouteChildren {
  AppSectorsIndexRoute: typeof AppSectorsIndexRoute
  AppSectorsCcSchedulerIndexRoute: typeof AppSectorsCcSchedulerIndexRoute
  AppSectorsDiagnosticsIndexRoute: typeof AppSectorsDiagnosticsIndexRoute
  AppSectorsExpirationIndexRoute: typeof AppSectorsExpirationIndexRoute
}

const AppSectorsRouteRouteChildren: AppSectorsRouteRouteChildren = {
  AppSectorsIndexRoute: AppSectorsIndexRoute,
  AppSectorsCcSchedulerIndexRoute: AppSectorsCcSchedulerIndexRoute,
  AppSectorsDiagnosticsIndexRoute: AppSectorsDiagnosticsIndexRoute,
  AppSectorsExpirationIndexRoute: AppSectorsExpirationIndexRoute,
}

const AppSectorsRouteRouteWithChildren = AppSectorsRouteRoute._addFileChildren(
  AppSectorsRouteRouteChildren,
)

interface AppStoragePathsRouteRouteChildren {
  AppStoragePathsStorageIdRoute: typeof AppStoragePathsStorageIdRoute
  AppStoragePathsIndexRoute: typeof AppStoragePathsIndexRoute
}

const AppStoragePathsRouteRouteChildren: AppStoragePathsRouteRouteChildren = {
  AppStoragePathsStorageIdRoute: AppStoragePathsStorageIdRoute,
  AppStoragePathsIndexRoute: AppStoragePathsIndexRoute,
}

const AppStoragePathsRouteRouteWithChildren =
  AppStoragePathsRouteRoute._addFileChildren(AppStoragePathsRouteRouteChildren)

interface AppStorageRouteRouteChildren {
  AppStoragePathsRouteRoute: typeof AppStoragePathsRouteRouteWithChildren
  AppStorageGcRoute: typeof AppStorageGcRoute
  AppStorageUsageRoute: typeof AppStorageUsageRoute
  AppStorageIndexRoute: typeof AppStorageIndexRoute
}

const AppStorageRouteRouteChildren: AppStorageRouteRouteChildren = {
  AppStoragePathsRouteRoute: AppStoragePathsRouteRouteWithChildren,
  AppStorageGcRoute: AppStorageGcRoute,
  AppStorageUsageRoute: AppStorageUsageRoute,
  AppStorageIndexRoute: AppStorageIndexRoute,
}

const AppStorageRouteRouteWithChildren = AppStorageRouteRoute._addFileChildren(
  AppStorageRouteRouteChildren,
)

interface AppTasksRouteRouteChildren {
  AppTasksActiveRoute: typeof AppTasksActiveRoute
  AppTasksAnalysisRoute: typeof AppTasksAnalysisRoute
  AppTasksHistoryRoute: typeof AppTasksHistoryRoute
  AppTasksOverviewRoute: typeof AppTasksOverviewRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteRouteChildren: AppTasksRouteRouteChildren = {
  AppTasksActiveRoute: AppTasksActiveRoute,
  AppTasksAnalysisRoute: AppTasksAnalysisRoute,
  AppTasksHistoryRoute: AppTasksHistoryRoute,
  AppTasksOverviewRoute: AppTasksOverviewRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteRouteWithChildren = AppTasksRouteRoute._addFileChildren(
  AppTasksRouteRouteChildren,
)

interface AppWalletsRouteRouteChildren {
  AppWalletsBalanceManagerRoute: typeof AppWalletsBalanceManagerRoute
  AppWalletsListRoute: typeof AppWalletsListRoute
  AppWalletsMessagesRoute: typeof AppWalletsMessagesRoute
  AppWalletsIndexRoute: typeof AppWalletsIndexRoute
}

const AppWalletsRouteRouteChildren: AppWalletsRouteRouteChildren = {
  AppWalletsBalanceManagerRoute: AppWalletsBalanceManagerRoute,
  AppWalletsListRoute: AppWalletsListRoute,
  AppWalletsMessagesRoute: AppWalletsMessagesRoute,
  AppWalletsIndexRoute: AppWalletsIndexRoute,
}

const AppWalletsRouteRouteWithChildren = AppWalletsRouteRoute._addFileChildren(
  AppWalletsRouteRouteChildren,
)

interface AppRouteChildren {
  AppIpniRouteRoute: typeof AppIpniRouteRouteWithChildren
  AppMachinesRouteRoute: typeof AppMachinesRouteRouteWithChildren
  AppMarketRouteRoute: typeof AppMarketRouteRouteWithChildren
  AppPdpRouteRoute: typeof AppPdpRouteRouteWithChildren
  AppPipelineRouteRoute: typeof AppPipelineRouteRouteWithChildren
  AppProofShareRouteRoute: typeof AppProofShareRouteRouteWithChildren
  AppSectorsRouteRoute: typeof AppSectorsRouteRouteWithChildren
  AppStorageRouteRoute: typeof AppStorageRouteRouteWithChildren
  AppTasksRouteRoute: typeof AppTasksRouteRouteWithChildren
  AppWalletsRouteRoute: typeof AppWalletsRouteRouteWithChildren
  AppActorIdRoute: typeof AppActorIdRoute
  AppActorIndexRoute: typeof AppActorIndexRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppOverviewIndexRoute: typeof AppOverviewIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIpniRouteRoute: AppIpniRouteRouteWithChildren,
  AppMachinesRouteRoute: AppMachinesRouteRouteWithChildren,
  AppMarketRouteRoute: AppMarketRouteRouteWithChildren,
  AppPdpRouteRoute: AppPdpRouteRouteWithChildren,
  AppPipelineRouteRoute: AppPipelineRouteRouteWithChildren,
  AppProofShareRouteRoute: AppProofShareRouteRouteWithChildren,
  AppSectorsRouteRoute: AppSectorsRouteRouteWithChildren,
  AppStorageRouteRoute: AppStorageRouteRouteWithChildren,
  AppTasksRouteRoute: AppTasksRouteRouteWithChildren,
  AppWalletsRouteRoute: AppWalletsRouteRouteWithChildren,
  AppActorIdRoute: AppActorIdRoute,
  AppActorIndexRoute: AppActorIndexRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppOverviewIndexRoute: AppOverviewIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
