/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SetupRouteImport } from "./routes/setup"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppTasksRouteRouteImport } from "./routes/_app/tasks/route"
import { Route as AppSectorsRouteRouteImport } from "./routes/_app/sectors/route"
import { Route as AppPipelineRouteRouteImport } from "./routes/_app/pipeline/route"
import { Route as AppMarketRouteRouteImport } from "./routes/_app/market/route"
import { Route as AppWalletsIndexRouteImport } from "./routes/_app/wallets/index"
import { Route as AppTasksIndexRouteImport } from "./routes/_app/tasks/index"
import { Route as AppStorageIndexRouteImport } from "./routes/_app/storage/index"
import { Route as AppSectorsIndexRouteImport } from "./routes/_app/sectors/index"
import { Route as AppProofShareIndexRouteImport } from "./routes/_app/proof-share/index"
import { Route as AppPipelineIndexRouteImport } from "./routes/_app/pipeline/index"
import { Route as AppPdpIndexRouteImport } from "./routes/_app/pdp/index"
import { Route as AppOverviewIndexRouteImport } from "./routes/_app/overview/index"
import { Route as AppMarketIndexRouteImport } from "./routes/_app/market/index"
import { Route as AppMachinesIndexRouteImport } from "./routes/_app/machines/index"
import { Route as AppIpniIndexRouteImport } from "./routes/_app/ipni/index"
import { Route as AppConfigIndexRouteImport } from "./routes/_app/config/index"
import { Route as AppAlertsIndexRouteImport } from "./routes/_app/alerts/index"
import { Route as AppActorIndexRouteImport } from "./routes/_app/actor/index"
import { Route as AppTasksOverviewRouteImport } from "./routes/_app/tasks/overview"
import { Route as AppTasksHistoryRouteImport } from "./routes/_app/tasks/history"
import { Route as AppTasksActiveRouteImport } from "./routes/_app/tasks/active"
import { Route as AppPipelineStatsRouteImport } from "./routes/_app/pipeline/stats"
import { Route as AppPipelineSnapRouteImport } from "./routes/_app/pipeline/snap"
import { Route as AppPipelinePorepRouteImport } from "./routes/_app/pipeline/porep"
import { Route as AppMarketPiecesRouteImport } from "./routes/_app/market/pieces"
import { Route as AppMarketPendingRouteImport } from "./routes/_app/market/pending"
import { Route as AppMarketBalanceRouteImport } from "./routes/_app/market/balance"
import { Route as AppMarketAsksRouteImport } from "./routes/_app/market/asks"
import { Route as AppMachinesIdRouteImport } from "./routes/_app/machines/$id"
import { Route as AppActorIdRouteImport } from "./routes/_app/actor/$id"
import { Route as AppSectorsExpirationIndexRouteImport } from "./routes/_app/sectors/expiration/index"
import { Route as AppSectorsDiagnosticsIndexRouteImport } from "./routes/_app/sectors/diagnostics/index"
import { Route as AppSectorsCcSchedulerIndexRouteImport } from "./routes/_app/sectors/cc-scheduler/index"
import { Route as AppMarketSettingsIndexRouteImport } from "./routes/_app/market/settings/index"
import { Route as AppMarketMk20DealsRouteImport } from "./routes/_app/market/mk20/deals"
import { Route as AppMarketMk12DealsRouteImport } from "./routes/_app/market/mk12/deals"

const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AppRoute,
} as any)
const AppSectorsRouteRoute = AppSectorsRouteRouteImport.update({
  id: "/sectors",
  path: "/sectors",
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRouteRoute = AppPipelineRouteRouteImport.update({
  id: "/pipeline",
  path: "/pipeline",
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRouteRoute = AppMarketRouteRouteImport.update({
  id: "/market",
  path: "/market",
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsIndexRoute = AppWalletsIndexRouteImport.update({
  id: "/wallets/",
  path: "/wallets/",
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppStorageIndexRoute = AppStorageIndexRouteImport.update({
  id: "/storage/",
  path: "/storage/",
  getParentRoute: () => AppRoute,
} as any)
const AppSectorsIndexRoute = AppSectorsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppSectorsRouteRoute,
} as any)
const AppProofShareIndexRoute = AppProofShareIndexRouteImport.update({
  id: "/proof-share/",
  path: "/proof-share/",
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineIndexRoute = AppPipelineIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppPdpIndexRoute = AppPdpIndexRouteImport.update({
  id: "/pdp/",
  path: "/pdp/",
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewIndexRoute = AppOverviewIndexRouteImport.update({
  id: "/overview/",
  path: "/overview/",
  getParentRoute: () => AppRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMachinesIndexRoute = AppMachinesIndexRouteImport.update({
  id: "/machines/",
  path: "/machines/",
  getParentRoute: () => AppRoute,
} as any)
const AppIpniIndexRoute = AppIpniIndexRouteImport.update({
  id: "/ipni/",
  path: "/ipni/",
  getParentRoute: () => AppRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: "/config/",
  path: "/config/",
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: "/alerts/",
  path: "/alerts/",
  getParentRoute: () => AppRoute,
} as any)
const AppActorIndexRoute = AppActorIndexRouteImport.update({
  id: "/actor/",
  path: "/actor/",
  getParentRoute: () => AppRoute,
} as any)
const AppTasksOverviewRoute = AppTasksOverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksHistoryRoute = AppTasksHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksActiveRoute = AppTasksActiveRouteImport.update({
  id: "/active",
  path: "/active",
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppPipelineStatsRoute = AppPipelineStatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppPipelineSnapRoute = AppPipelineSnapRouteImport.update({
  id: "/snap",
  path: "/snap",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppPipelinePorepRoute = AppPipelinePorepRouteImport.update({
  id: "/porep",
  path: "/porep",
  getParentRoute: () => AppPipelineRouteRoute,
} as any)
const AppMarketPiecesRoute = AppMarketPiecesRouteImport.update({
  id: "/pieces",
  path: "/pieces",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketPendingRoute = AppMarketPendingRouteImport.update({
  id: "/pending",
  path: "/pending",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketBalanceRoute = AppMarketBalanceRouteImport.update({
  id: "/balance",
  path: "/balance",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketAsksRoute = AppMarketAsksRouteImport.update({
  id: "/asks",
  path: "/asks",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMachinesIdRoute = AppMachinesIdRouteImport.update({
  id: "/machines/$id",
  path: "/machines/$id",
  getParentRoute: () => AppRoute,
} as any)
const AppActorIdRoute = AppActorIdRouteImport.update({
  id: "/actor/$id",
  path: "/actor/$id",
  getParentRoute: () => AppRoute,
} as any)
const AppSectorsExpirationIndexRoute =
  AppSectorsExpirationIndexRouteImport.update({
    id: "/expiration/",
    path: "/expiration/",
    getParentRoute: () => AppSectorsRouteRoute,
  } as any)
const AppSectorsDiagnosticsIndexRoute =
  AppSectorsDiagnosticsIndexRouteImport.update({
    id: "/diagnostics/",
    path: "/diagnostics/",
    getParentRoute: () => AppSectorsRouteRoute,
  } as any)
const AppSectorsCcSchedulerIndexRoute =
  AppSectorsCcSchedulerIndexRouteImport.update({
    id: "/cc-scheduler/",
    path: "/cc-scheduler/",
    getParentRoute: () => AppSectorsRouteRoute,
  } as any)
const AppMarketSettingsIndexRoute = AppMarketSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketMk20DealsRoute = AppMarketMk20DealsRouteImport.update({
  id: "/mk20/deals",
  path: "/mk20/deals",
  getParentRoute: () => AppMarketRouteRoute,
} as any)
const AppMarketMk12DealsRoute = AppMarketMk12DealsRouteImport.update({
  id: "/mk12/deals",
  path: "/mk12/deals",
  getParentRoute: () => AppMarketRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/setup": typeof SetupRoute
  "/market": typeof AppMarketRouteRouteWithChildren
  "/pipeline": typeof AppPipelineRouteRouteWithChildren
  "/sectors": typeof AppSectorsRouteRouteWithChildren
  "/tasks": typeof AppTasksRouteRouteWithChildren
  "/actor/$id": typeof AppActorIdRoute
  "/machines/$id": typeof AppMachinesIdRoute
  "/market/asks": typeof AppMarketAsksRoute
  "/market/balance": typeof AppMarketBalanceRoute
  "/market/pending": typeof AppMarketPendingRoute
  "/market/pieces": typeof AppMarketPiecesRoute
  "/pipeline/porep": typeof AppPipelinePorepRoute
  "/pipeline/snap": typeof AppPipelineSnapRoute
  "/pipeline/stats": typeof AppPipelineStatsRoute
  "/tasks/active": typeof AppTasksActiveRoute
  "/tasks/history": typeof AppTasksHistoryRoute
  "/tasks/overview": typeof AppTasksOverviewRoute
  "/actor/": typeof AppActorIndexRoute
  "/alerts/": typeof AppAlertsIndexRoute
  "/config/": typeof AppConfigIndexRoute
  "/ipni/": typeof AppIpniIndexRoute
  "/machines/": typeof AppMachinesIndexRoute
  "/market/": typeof AppMarketIndexRoute
  "/overview/": typeof AppOverviewIndexRoute
  "/pdp/": typeof AppPdpIndexRoute
  "/pipeline/": typeof AppPipelineIndexRoute
  "/proof-share/": typeof AppProofShareIndexRoute
  "/sectors/": typeof AppSectorsIndexRoute
  "/storage/": typeof AppStorageIndexRoute
  "/tasks/": typeof AppTasksIndexRoute
  "/wallets/": typeof AppWalletsIndexRoute
  "/market/mk12/deals": typeof AppMarketMk12DealsRoute
  "/market/mk20/deals": typeof AppMarketMk20DealsRoute
  "/market/settings/": typeof AppMarketSettingsIndexRoute
  "/sectors/cc-scheduler/": typeof AppSectorsCcSchedulerIndexRoute
  "/sectors/diagnostics/": typeof AppSectorsDiagnosticsIndexRoute
  "/sectors/expiration/": typeof AppSectorsExpirationIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/setup": typeof SetupRoute
  "/actor/$id": typeof AppActorIdRoute
  "/machines/$id": typeof AppMachinesIdRoute
  "/market/asks": typeof AppMarketAsksRoute
  "/market/balance": typeof AppMarketBalanceRoute
  "/market/pending": typeof AppMarketPendingRoute
  "/market/pieces": typeof AppMarketPiecesRoute
  "/pipeline/porep": typeof AppPipelinePorepRoute
  "/pipeline/snap": typeof AppPipelineSnapRoute
  "/pipeline/stats": typeof AppPipelineStatsRoute
  "/tasks/active": typeof AppTasksActiveRoute
  "/tasks/history": typeof AppTasksHistoryRoute
  "/tasks/overview": typeof AppTasksOverviewRoute
  "/actor": typeof AppActorIndexRoute
  "/alerts": typeof AppAlertsIndexRoute
  "/config": typeof AppConfigIndexRoute
  "/ipni": typeof AppIpniIndexRoute
  "/machines": typeof AppMachinesIndexRoute
  "/market": typeof AppMarketIndexRoute
  "/overview": typeof AppOverviewIndexRoute
  "/pdp": typeof AppPdpIndexRoute
  "/pipeline": typeof AppPipelineIndexRoute
  "/proof-share": typeof AppProofShareIndexRoute
  "/sectors": typeof AppSectorsIndexRoute
  "/storage": typeof AppStorageIndexRoute
  "/tasks": typeof AppTasksIndexRoute
  "/wallets": typeof AppWalletsIndexRoute
  "/market/mk12/deals": typeof AppMarketMk12DealsRoute
  "/market/mk20/deals": typeof AppMarketMk20DealsRoute
  "/market/settings": typeof AppMarketSettingsIndexRoute
  "/sectors/cc-scheduler": typeof AppSectorsCcSchedulerIndexRoute
  "/sectors/diagnostics": typeof AppSectorsDiagnosticsIndexRoute
  "/sectors/expiration": typeof AppSectorsExpirationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/setup": typeof SetupRoute
  "/_app/market": typeof AppMarketRouteRouteWithChildren
  "/_app/pipeline": typeof AppPipelineRouteRouteWithChildren
  "/_app/sectors": typeof AppSectorsRouteRouteWithChildren
  "/_app/tasks": typeof AppTasksRouteRouteWithChildren
  "/_app/actor/$id": typeof AppActorIdRoute
  "/_app/machines/$id": typeof AppMachinesIdRoute
  "/_app/market/asks": typeof AppMarketAsksRoute
  "/_app/market/balance": typeof AppMarketBalanceRoute
  "/_app/market/pending": typeof AppMarketPendingRoute
  "/_app/market/pieces": typeof AppMarketPiecesRoute
  "/_app/pipeline/porep": typeof AppPipelinePorepRoute
  "/_app/pipeline/snap": typeof AppPipelineSnapRoute
  "/_app/pipeline/stats": typeof AppPipelineStatsRoute
  "/_app/tasks/active": typeof AppTasksActiveRoute
  "/_app/tasks/history": typeof AppTasksHistoryRoute
  "/_app/tasks/overview": typeof AppTasksOverviewRoute
  "/_app/actor/": typeof AppActorIndexRoute
  "/_app/alerts/": typeof AppAlertsIndexRoute
  "/_app/config/": typeof AppConfigIndexRoute
  "/_app/ipni/": typeof AppIpniIndexRoute
  "/_app/machines/": typeof AppMachinesIndexRoute
  "/_app/market/": typeof AppMarketIndexRoute
  "/_app/overview/": typeof AppOverviewIndexRoute
  "/_app/pdp/": typeof AppPdpIndexRoute
  "/_app/pipeline/": typeof AppPipelineIndexRoute
  "/_app/proof-share/": typeof AppProofShareIndexRoute
  "/_app/sectors/": typeof AppSectorsIndexRoute
  "/_app/storage/": typeof AppStorageIndexRoute
  "/_app/tasks/": typeof AppTasksIndexRoute
  "/_app/wallets/": typeof AppWalletsIndexRoute
  "/_app/market/mk12/deals": typeof AppMarketMk12DealsRoute
  "/_app/market/mk20/deals": typeof AppMarketMk20DealsRoute
  "/_app/market/settings/": typeof AppMarketSettingsIndexRoute
  "/_app/sectors/cc-scheduler/": typeof AppSectorsCcSchedulerIndexRoute
  "/_app/sectors/diagnostics/": typeof AppSectorsDiagnosticsIndexRoute
  "/_app/sectors/expiration/": typeof AppSectorsExpirationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/setup"
    | "/market"
    | "/pipeline"
    | "/sectors"
    | "/tasks"
    | "/actor/$id"
    | "/machines/$id"
    | "/market/asks"
    | "/market/balance"
    | "/market/pending"
    | "/market/pieces"
    | "/pipeline/porep"
    | "/pipeline/snap"
    | "/pipeline/stats"
    | "/tasks/active"
    | "/tasks/history"
    | "/tasks/overview"
    | "/actor/"
    | "/alerts/"
    | "/config/"
    | "/ipni/"
    | "/machines/"
    | "/market/"
    | "/overview/"
    | "/pdp/"
    | "/pipeline/"
    | "/proof-share/"
    | "/sectors/"
    | "/storage/"
    | "/tasks/"
    | "/wallets/"
    | "/market/mk12/deals"
    | "/market/mk20/deals"
    | "/market/settings/"
    | "/sectors/cc-scheduler/"
    | "/sectors/diagnostics/"
    | "/sectors/expiration/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/setup"
    | "/actor/$id"
    | "/machines/$id"
    | "/market/asks"
    | "/market/balance"
    | "/market/pending"
    | "/market/pieces"
    | "/pipeline/porep"
    | "/pipeline/snap"
    | "/pipeline/stats"
    | "/tasks/active"
    | "/tasks/history"
    | "/tasks/overview"
    | "/actor"
    | "/alerts"
    | "/config"
    | "/ipni"
    | "/machines"
    | "/market"
    | "/overview"
    | "/pdp"
    | "/pipeline"
    | "/proof-share"
    | "/sectors"
    | "/storage"
    | "/tasks"
    | "/wallets"
    | "/market/mk12/deals"
    | "/market/mk20/deals"
    | "/market/settings"
    | "/sectors/cc-scheduler"
    | "/sectors/diagnostics"
    | "/sectors/expiration"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/setup"
    | "/_app/market"
    | "/_app/pipeline"
    | "/_app/sectors"
    | "/_app/tasks"
    | "/_app/actor/$id"
    | "/_app/machines/$id"
    | "/_app/market/asks"
    | "/_app/market/balance"
    | "/_app/market/pending"
    | "/_app/market/pieces"
    | "/_app/pipeline/porep"
    | "/_app/pipeline/snap"
    | "/_app/pipeline/stats"
    | "/_app/tasks/active"
    | "/_app/tasks/history"
    | "/_app/tasks/overview"
    | "/_app/actor/"
    | "/_app/alerts/"
    | "/_app/config/"
    | "/_app/ipni/"
    | "/_app/machines/"
    | "/_app/market/"
    | "/_app/overview/"
    | "/_app/pdp/"
    | "/_app/pipeline/"
    | "/_app/proof-share/"
    | "/_app/sectors/"
    | "/_app/storage/"
    | "/_app/tasks/"
    | "/_app/wallets/"
    | "/_app/market/mk12/deals"
    | "/_app/market/mk20/deals"
    | "/_app/market/settings/"
    | "/_app/sectors/cc-scheduler/"
    | "/_app/sectors/diagnostics/"
    | "/_app/sectors/expiration/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/setup": {
      id: "/setup"
      path: "/setup"
      fullPath: "/setup"
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/tasks": {
      id: "/_app/tasks"
      path: "/tasks"
      fullPath: "/tasks"
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/sectors": {
      id: "/_app/sectors"
      path: "/sectors"
      fullPath: "/sectors"
      preLoaderRoute: typeof AppSectorsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/pipeline": {
      id: "/_app/pipeline"
      path: "/pipeline"
      fullPath: "/pipeline"
      preLoaderRoute: typeof AppPipelineRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/market": {
      id: "/_app/market"
      path: "/market"
      fullPath: "/market"
      preLoaderRoute: typeof AppMarketRouteRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/wallets/": {
      id: "/_app/wallets/"
      path: "/wallets"
      fullPath: "/wallets/"
      preLoaderRoute: typeof AppWalletsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tasks/": {
      id: "/_app/tasks/"
      path: "/"
      fullPath: "/tasks/"
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/storage/": {
      id: "/_app/storage/"
      path: "/storage"
      fullPath: "/storage/"
      preLoaderRoute: typeof AppStorageIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/sectors/": {
      id: "/_app/sectors/"
      path: "/"
      fullPath: "/sectors/"
      preLoaderRoute: typeof AppSectorsIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/proof-share/": {
      id: "/_app/proof-share/"
      path: "/proof-share"
      fullPath: "/proof-share/"
      preLoaderRoute: typeof AppProofShareIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/pipeline/": {
      id: "/_app/pipeline/"
      path: "/"
      fullPath: "/pipeline/"
      preLoaderRoute: typeof AppPipelineIndexRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/pdp/": {
      id: "/_app/pdp/"
      path: "/pdp"
      fullPath: "/pdp/"
      preLoaderRoute: typeof AppPdpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/overview/": {
      id: "/_app/overview/"
      path: "/overview"
      fullPath: "/overview/"
      preLoaderRoute: typeof AppOverviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/market/": {
      id: "/_app/market/"
      path: "/"
      fullPath: "/market/"
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/machines/": {
      id: "/_app/machines/"
      path: "/machines"
      fullPath: "/machines/"
      preLoaderRoute: typeof AppMachinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/ipni/": {
      id: "/_app/ipni/"
      path: "/ipni"
      fullPath: "/ipni/"
      preLoaderRoute: typeof AppIpniIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/config/": {
      id: "/_app/config/"
      path: "/config"
      fullPath: "/config/"
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/alerts/": {
      id: "/_app/alerts/"
      path: "/alerts"
      fullPath: "/alerts/"
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/actor/": {
      id: "/_app/actor/"
      path: "/actor"
      fullPath: "/actor/"
      preLoaderRoute: typeof AppActorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tasks/overview": {
      id: "/_app/tasks/overview"
      path: "/overview"
      fullPath: "/tasks/overview"
      preLoaderRoute: typeof AppTasksOverviewRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/tasks/history": {
      id: "/_app/tasks/history"
      path: "/history"
      fullPath: "/tasks/history"
      preLoaderRoute: typeof AppTasksHistoryRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/tasks/active": {
      id: "/_app/tasks/active"
      path: "/active"
      fullPath: "/tasks/active"
      preLoaderRoute: typeof AppTasksActiveRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    "/_app/pipeline/stats": {
      id: "/_app/pipeline/stats"
      path: "/stats"
      fullPath: "/pipeline/stats"
      preLoaderRoute: typeof AppPipelineStatsRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/pipeline/snap": {
      id: "/_app/pipeline/snap"
      path: "/snap"
      fullPath: "/pipeline/snap"
      preLoaderRoute: typeof AppPipelineSnapRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/pipeline/porep": {
      id: "/_app/pipeline/porep"
      path: "/porep"
      fullPath: "/pipeline/porep"
      preLoaderRoute: typeof AppPipelinePorepRouteImport
      parentRoute: typeof AppPipelineRouteRoute
    }
    "/_app/market/pieces": {
      id: "/_app/market/pieces"
      path: "/pieces"
      fullPath: "/market/pieces"
      preLoaderRoute: typeof AppMarketPiecesRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/pending": {
      id: "/_app/market/pending"
      path: "/pending"
      fullPath: "/market/pending"
      preLoaderRoute: typeof AppMarketPendingRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/balance": {
      id: "/_app/market/balance"
      path: "/balance"
      fullPath: "/market/balance"
      preLoaderRoute: typeof AppMarketBalanceRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/asks": {
      id: "/_app/market/asks"
      path: "/asks"
      fullPath: "/market/asks"
      preLoaderRoute: typeof AppMarketAsksRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/machines/$id": {
      id: "/_app/machines/$id"
      path: "/machines/$id"
      fullPath: "/machines/$id"
      preLoaderRoute: typeof AppMachinesIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/actor/$id": {
      id: "/_app/actor/$id"
      path: "/actor/$id"
      fullPath: "/actor/$id"
      preLoaderRoute: typeof AppActorIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/sectors/expiration/": {
      id: "/_app/sectors/expiration/"
      path: "/expiration"
      fullPath: "/sectors/expiration/"
      preLoaderRoute: typeof AppSectorsExpirationIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/sectors/diagnostics/": {
      id: "/_app/sectors/diagnostics/"
      path: "/diagnostics"
      fullPath: "/sectors/diagnostics/"
      preLoaderRoute: typeof AppSectorsDiagnosticsIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/sectors/cc-scheduler/": {
      id: "/_app/sectors/cc-scheduler/"
      path: "/cc-scheduler"
      fullPath: "/sectors/cc-scheduler/"
      preLoaderRoute: typeof AppSectorsCcSchedulerIndexRouteImport
      parentRoute: typeof AppSectorsRouteRoute
    }
    "/_app/market/settings/": {
      id: "/_app/market/settings/"
      path: "/settings"
      fullPath: "/market/settings/"
      preLoaderRoute: typeof AppMarketSettingsIndexRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/mk20/deals": {
      id: "/_app/market/mk20/deals"
      path: "/mk20/deals"
      fullPath: "/market/mk20/deals"
      preLoaderRoute: typeof AppMarketMk20DealsRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
    "/_app/market/mk12/deals": {
      id: "/_app/market/mk12/deals"
      path: "/mk12/deals"
      fullPath: "/market/mk12/deals"
      preLoaderRoute: typeof AppMarketMk12DealsRouteImport
      parentRoute: typeof AppMarketRouteRoute
    }
  }
}

interface AppMarketRouteRouteChildren {
  AppMarketAsksRoute: typeof AppMarketAsksRoute
  AppMarketBalanceRoute: typeof AppMarketBalanceRoute
  AppMarketPendingRoute: typeof AppMarketPendingRoute
  AppMarketPiecesRoute: typeof AppMarketPiecesRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppMarketMk12DealsRoute: typeof AppMarketMk12DealsRoute
  AppMarketMk20DealsRoute: typeof AppMarketMk20DealsRoute
  AppMarketSettingsIndexRoute: typeof AppMarketSettingsIndexRoute
}

const AppMarketRouteRouteChildren: AppMarketRouteRouteChildren = {
  AppMarketAsksRoute: AppMarketAsksRoute,
  AppMarketBalanceRoute: AppMarketBalanceRoute,
  AppMarketPendingRoute: AppMarketPendingRoute,
  AppMarketPiecesRoute: AppMarketPiecesRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppMarketMk12DealsRoute: AppMarketMk12DealsRoute,
  AppMarketMk20DealsRoute: AppMarketMk20DealsRoute,
  AppMarketSettingsIndexRoute: AppMarketSettingsIndexRoute,
}

const AppMarketRouteRouteWithChildren = AppMarketRouteRoute._addFileChildren(
  AppMarketRouteRouteChildren,
)

interface AppPipelineRouteRouteChildren {
  AppPipelinePorepRoute: typeof AppPipelinePorepRoute
  AppPipelineSnapRoute: typeof AppPipelineSnapRoute
  AppPipelineStatsRoute: typeof AppPipelineStatsRoute
  AppPipelineIndexRoute: typeof AppPipelineIndexRoute
}

const AppPipelineRouteRouteChildren: AppPipelineRouteRouteChildren = {
  AppPipelinePorepRoute: AppPipelinePorepRoute,
  AppPipelineSnapRoute: AppPipelineSnapRoute,
  AppPipelineStatsRoute: AppPipelineStatsRoute,
  AppPipelineIndexRoute: AppPipelineIndexRoute,
}

const AppPipelineRouteRouteWithChildren =
  AppPipelineRouteRoute._addFileChildren(AppPipelineRouteRouteChildren)

interface AppSectorsRouteRouteChildren {
  AppSectorsIndexRoute: typeof AppSectorsIndexRoute
  AppSectorsCcSchedulerIndexRoute: typeof AppSectorsCcSchedulerIndexRoute
  AppSectorsDiagnosticsIndexRoute: typeof AppSectorsDiagnosticsIndexRoute
  AppSectorsExpirationIndexRoute: typeof AppSectorsExpirationIndexRoute
}

const AppSectorsRouteRouteChildren: AppSectorsRouteRouteChildren = {
  AppSectorsIndexRoute: AppSectorsIndexRoute,
  AppSectorsCcSchedulerIndexRoute: AppSectorsCcSchedulerIndexRoute,
  AppSectorsDiagnosticsIndexRoute: AppSectorsDiagnosticsIndexRoute,
  AppSectorsExpirationIndexRoute: AppSectorsExpirationIndexRoute,
}

const AppSectorsRouteRouteWithChildren = AppSectorsRouteRoute._addFileChildren(
  AppSectorsRouteRouteChildren,
)

interface AppTasksRouteRouteChildren {
  AppTasksActiveRoute: typeof AppTasksActiveRoute
  AppTasksHistoryRoute: typeof AppTasksHistoryRoute
  AppTasksOverviewRoute: typeof AppTasksOverviewRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteRouteChildren: AppTasksRouteRouteChildren = {
  AppTasksActiveRoute: AppTasksActiveRoute,
  AppTasksHistoryRoute: AppTasksHistoryRoute,
  AppTasksOverviewRoute: AppTasksOverviewRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteRouteWithChildren = AppTasksRouteRoute._addFileChildren(
  AppTasksRouteRouteChildren,
)

interface AppRouteChildren {
  AppMarketRouteRoute: typeof AppMarketRouteRouteWithChildren
  AppPipelineRouteRoute: typeof AppPipelineRouteRouteWithChildren
  AppSectorsRouteRoute: typeof AppSectorsRouteRouteWithChildren
  AppTasksRouteRoute: typeof AppTasksRouteRouteWithChildren
  AppActorIdRoute: typeof AppActorIdRoute
  AppMachinesIdRoute: typeof AppMachinesIdRoute
  AppActorIndexRoute: typeof AppActorIndexRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppIpniIndexRoute: typeof AppIpniIndexRoute
  AppMachinesIndexRoute: typeof AppMachinesIndexRoute
  AppOverviewIndexRoute: typeof AppOverviewIndexRoute
  AppPdpIndexRoute: typeof AppPdpIndexRoute
  AppProofShareIndexRoute: typeof AppProofShareIndexRoute
  AppStorageIndexRoute: typeof AppStorageIndexRoute
  AppWalletsIndexRoute: typeof AppWalletsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMarketRouteRoute: AppMarketRouteRouteWithChildren,
  AppPipelineRouteRoute: AppPipelineRouteRouteWithChildren,
  AppSectorsRouteRoute: AppSectorsRouteRouteWithChildren,
  AppTasksRouteRoute: AppTasksRouteRouteWithChildren,
  AppActorIdRoute: AppActorIdRoute,
  AppMachinesIdRoute: AppMachinesIdRoute,
  AppActorIndexRoute: AppActorIndexRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppIpniIndexRoute: AppIpniIndexRoute,
  AppMachinesIndexRoute: AppMachinesIndexRoute,
  AppOverviewIndexRoute: AppOverviewIndexRoute,
  AppPdpIndexRoute: AppPdpIndexRoute,
  AppProofShareIndexRoute: AppProofShareIndexRoute,
  AppStorageIndexRoute: AppStorageIndexRoute,
  AppWalletsIndexRoute: AppWalletsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
